version: "3"
services: 
  client:
    stdin_open: true
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes: 
      - './client:/app'
      - '/app/node_modules'
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - './server:/app'
      - '/app/node_modules'
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports: 
      - '80:80'
    depends_on: 
      - api
      - client
    restart: always